"""Обнаружение WAF и безопасные попытки обхода фильтров (маркерные payload'ы)."""

from __future__ import annotations

import re
from typing import List, Optional, Sequence, Tuple
from urllib.parse import quote, urljoin

from ..http_client import HttpClient
from ..models import CONFIG, CONFIRMED, HIGH, INFO, LOW, MEDIUM, SUSPECTED, VULN, Finding, Page
from ..utils import build_url, query_params, truncate

MARKER = "BAUMAN_TEST_92841"
PEEK = 900

WAF_SIGNATURES: Tuple[Tuple[str, re.Pattern], ...] = (
    ("Cloudflare", re.compile(r"(?i)cloudflare|cf-ray|attention required|cf-chl")),
    ("AWS WAF / ALB", re.compile(r"(?i)awselb|request blocked|aws waf|x-amzn-waf")),
    ("ModSecurity", re.compile(r"(?i)mod_security|not acceptable|this error was generated by mod_security")),
    ("Imperva / Incapsula", re.compile(r"(?i)incapsula|imperva|_incap_")),
    ("Akamai", re.compile(r"(?i)akamai|access denied.*reference")),
    ("Sucuri", re.compile(r"(?i)sucuri|access denied - sucuri")),
    ("Wordfence", re.compile(r"(?i)wordfence|generated by wordfence")),
    ("Generic WAF", re.compile(r"(?i)web application firewall|request rejected|"
                               r"suspicious activity|security policy|blocked by")),
)

# Очевидная атака для детекта блокировки
PROBE_XSS = f"<script>alert('{MARKER}')</script>"
PROBE_SQLI = f"' OR '{MARKER}'='{MARKER}"

# Обфусцированные варианты (без реального эксплойта — только маркеры)
BYPASS_XSS: Tuple[str, ...] = (
    f"%3Cscript%3Ealert('{MARKER}')%3C%2Fscript%3E",
    f"<ScRiPt>alert('{MARKER}')</ScRiPt>",
    f"<img src=x onerror=alert('{MARKER}')>",
    f"<svg/onload=alert('{MARKER}')>",
    quote(f"<<script>alert('{MARKER}')//<</script>"),
)
BYPASS_SQLI: Tuple[str, ...] = (
    f"'/**/OR/**/'{MARKER}'='{MARKER}",
    f"'%20OR%20'{MARKER}'='{MARKER}",
    f"' OR '{MARKER}' LIKE '{MARKER}",
    f"1' OR '{MARKER}'='{MARKER}' -- ",
)


def run_waf_checks(
    client: HttpClient,
    base_url: str,
    pages: Sequence[Page],
    reserve: int = 0,
) -> List[Finding]:
    findings: List[Finding] = []
    waf_name, blocked = _detect_waf(client, base_url, pages, reserve)
    if waf_name:
        findings.append(
            Finding(
                url=base_url,
                title=f"Обнаружен веб-фильтр (WAF): {waf_name}",
                category=CONFIG,
                severity=INFO,
                recommendation="WAF снижает риск массовых атак, но не заменяет исправление "
                               "уязвимостей в коде. Проверьте, что легитимный трафик не режется, "
                               "и ведите мониторинг ложных срабатываний.",
                request="Пробный маркерный запрос с очевидным XSS/SQLi payload",
                evidence=truncate(blocked or waf_name, 500),
                confidence=CONFIRMED,
                kind="waf_detected",
            )
        )

    # Даже без явного имени WAF пробуем обход, если прямой payload режется
    findings.extend(_try_bypasses(client, pages, reserve, waf_name=waf_name))
    return findings


def _detect_waf(
    client: HttpClient,
    base_url: str,
    pages: Sequence[Page],
    reserve: int,
) -> Tuple[Optional[str], str]:
    target_url = _first_get_target(pages, base_url)
    if not client.can_request(reserve):
        return None, ""
    response = client.get(target_url, allow_redirects=True, max_body_bytes=PEEK, reserve=reserve)
    if response is None:
        return None, ""

    # Шлём явный XSS в параметр
    probe = _with_param(target_url, "q", PROBE_XSS)
    if not client.can_request(reserve):
        return _match_headers(response), _peek(response)
    blocked = client.get(probe, allow_redirects=True, max_body_bytes=PEEK, reserve=reserve)
    if blocked is None:
        return _match_headers(response), _peek(response)

    text = _peek(blocked)
    headers_blob = " ".join(f"{k}:{v}" for k, v in blocked.headers.items())
    blob = text + "\n" + headers_blob
    for name, pattern in WAF_SIGNATURES:
        if pattern.search(blob):
            return name, truncate(blob, 400)
    if blocked.status_code in (403, 406, 429, 503) and response.status_code == 200:
        return "Возможный WAF / фильтр запросов", truncate(
            f"Обычный ответ HTTP/{response.status_code}, "
            f"маркерный XSS → HTTP/{blocked.status_code}\n{text[:200]}",
            400,
        )
    # Иногда WAF отдаёт 200 с страницей блокировки
    if re.search(r"(?i)blocked|forbidden|not acceptable|security|firewall", text) and \
            MARKER not in text:
        return "Возможный WAF (страница блокировки)", truncate(text, 400)
    return _match_headers(response), ""


def _match_headers(response) -> Optional[str]:
    headers_blob = " ".join(f"{k}:{v}" for k, v in response.headers.items())
    for name, pattern in WAF_SIGNATURES:
        if pattern.search(headers_blob):
            return name
    return None


def _try_bypasses(
    client: HttpClient,
    pages: Sequence[Page],
    reserve: int,
    *,
    waf_name: Optional[str],
) -> List[Finding]:
    findings: List[Finding] = []
    targets = _injection_targets(pages)[:6]
    if not targets:
        return findings

    for page_url, param in targets:
        if not client.can_request(reserve):
            break
        # Прямой payload
        direct_url = _with_param(page_url, param, PROBE_XSS)
        direct = client.get(direct_url, allow_redirects=True, max_body_bytes=PEEK, reserve=reserve)
        if direct is None:
            continue
        direct_body = _peek(direct)
        direct_blocked = (
            direct.status_code in (403, 406, 429, 503)
            or (MARKER not in direct_body and re.search(
                r"(?i)blocked|forbidden|not acceptable|firewall", direct_body))
        )
        if not direct_blocked and MARKER in direct_body:
            # Уже отражается без обхода — классический XSS поймает active.py
            continue
        if not direct_blocked and not waf_name:
            continue

        for payload in BYPASS_XSS:
            if not client.can_request(reserve):
                break
            bypass_url = _with_param(page_url, param, payload)
            response = client.get(bypass_url, allow_redirects=True, max_body_bytes=PEEK,
                                  reserve=reserve)
            if response is None or response.status_code != 200:
                continue
            body = _peek(response)
            reflected = MARKER in body and (
                "<script" in body.lower()
                or "onerror=" in body.lower()
                or "onload=" in body.lower()
                or f"alert('{MARKER}')" in body
                or f"alert(\"{MARKER}\")" in body
            )
            if reflected and MARKER not in direct_body:
                findings.append(
                    Finding(
                        url=bypass_url,
                        title="Возможен обход WAF/фильтра: отражённый XSS после обфускации",
                        category=VULN,
                        severity=HIGH,
                        recommendation="Исправьте экранирование вывода на сервере. "
                                       "Не полагайтесь только на WAF: обфусцированные payload'ы "
                                       "часто проходят сигнатурные правила. Добавьте CSP.",
                        request=f"GET с обфусцированным XSS в «{param}»",
                        evidence=truncate(
                            f"Прямой payload → HTTP/{direct.status_code}, маркер не отражён/блок\n"
                            f"Обходной payload → HTTP/{response.status_code}, маркер отражён\n"
                            f"Фрагмент:\n{body[:350]}",
                            700,
                        ),
                        confidence=SUSPECTED,
                        kind="waf_bypass_xss",
                    )
                )
                return findings

        for payload in BYPASS_SQLI[:2]:
            if not client.can_request(reserve):
                break
            bypass_url = _with_param(page_url, param, payload)
            response = client.get(bypass_url, allow_redirects=True, max_body_bytes=PEEK,
                                  reserve=reserve)
            if response is None:
                continue
            body = _peek(response)
            if re.search(
                r"(?i)sql syntax|mysql_|pg_query|odbc|sqlite|"
                r"unclosed quotation|ORA-\d{5}",
                body,
            ) and not re.search(
                r"(?i)sql syntax|mysql_|pg_query",
                direct_body,
            ):
                findings.append(
                    Finding(
                        url=bypass_url,
                        title="Возможен обход WAF/фильтра: ошибка SQL после обфускации",
                        category=VULN,
                        severity=HIGH,
                        recommendation="Используйте параметризованные запросы. "
                                       "WAF не заменяет исправление SQL-инъекции.",
                        request=f"GET с обфусцированным SQLi в «{param}»",
                        evidence=truncate(
                            f"Прямой payload → HTTP/{direct.status_code}\n"
                            f"Обходной → HTTP/{response.status_code}\n{body[:350]}",
                            700,
                        ),
                        confidence=SUSPECTED,
                        kind="waf_bypass_sqli",
                    )
                )
                return findings
    return findings


def _first_get_target(pages: Sequence[Page], base_url: str) -> str:
    for page in pages:
        params = query_params(page.url)
        if params:
            return _with_param(page.url, params[0][0], "bauman")
        return page.url
    return urljoin(base_url, "/")


def _injection_targets(pages: Sequence[Page]) -> List[Tuple[str, str]]:
    out: List[Tuple[str, str]] = []
    seen = set()
    for page in pages:
        for name, _value in query_params(page.url):
            key = (urlparse_path(page.url), name)
            if not name or key in seen:
                continue
            seen.add(key)
            out.append((page.url, name))
    return out


def urlparse_path(url: str) -> str:
    from urllib.parse import urlparse as _up
    return _up(url).path


def _with_param(url: str, name: str, value: str) -> str:
    params = dict(query_params(url))
    params[name] = value
    if not params:
        params = {name: value}
    base = url.split("?", 1)[0]
    return build_url(base, list(params.items()))


def _peek(response) -> str:
    data = response.content or b""
    return data.decode(response.encoding or "utf-8", errors="replace")[:PEEK].replace("\r", "")
